version: '3.8'

services:
  openshift-mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: openshift-mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - KUBECONFIG=/app/.kube/config
    volumes:
      # Mount kubeconfig for cluster access
      - ${HOME}/.kube/config:/app/.kube/config:ro
      # Mount source code for development (optional)
      - ../index.js:/app/index.js:ro
      - ../package.json:/app/package.json:ro
    networks:
      - mcp-network
    stdin_open: true
    tty: true
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple web interface for testing
  mcp-test-client:
    image: node:18-alpine
    container_name: mcp-test-client
    working_dir: /app
    volumes:
      - ./test-client:/app
    command: >
      sh -c "
        if [ ! -f package.json ]; then
          npm init -y &&
          npm install @modelcontextprotocol/sdk
        fi &&
        tail -f /dev/null
      "
    networks:
      - mcp-network
    depends_on:
      - openshift-mcp-server

networks:
  mcp-network:
    driver: bridge

# Optional volumes for persistent data
volumes:
  mcp-data:
    driver: local 