---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-mcp-server
  namespace: default
  labels:
    app: openshift-mcp-server
    component: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-mcp-server
  labels:
    app: openshift-mcp-server
    component: monitoring
rules:
# Core API resources
- apiGroups: [""]
  resources:
    - nodes
    - nodes/status
    - nodes/metrics
    - pods
    - pods/status
    - pods/log
    - namespaces
    - services
    - endpoints
    - persistentvolumes
    - persistentvolumeclaims
    - configmaps
    - secrets
    - events
  verbs: ["get", "list", "watch"]

# Apps API resources
- apiGroups: ["apps"]
  resources:
    - deployments
    - deployments/status
    - replicasets
    - replicasets/status
    - daemonsets
    - daemonsets/status
    - statefulsets
    - statefulsets/status
  verbs: ["get", "list", "watch"]

# Extensions API resources
- apiGroups: ["extensions"]
  resources:
    - deployments
    - deployments/status
    - replicasets
    - replicasets/status
  verbs: ["get", "list", "watch"]

# Metrics API resources
- apiGroups: ["metrics.k8s.io"]
  resources:
    - nodes
    - pods
  verbs: ["get", "list"]

# Custom metrics API
- apiGroups: ["custom.metrics.k8s.io"]
  resources:
    - "*"
  verbs: ["get", "list"]

# Autoscaling resources
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]

# Policy resources
- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs: ["get", "list", "watch"]

# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources:
    - networkpolicies
    - ingresses
  verbs: ["get", "list", "watch"]

# Storage resources
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - volumeattachments
  verbs: ["get", "list", "watch"]

# OpenShift specific resources (if available)
- apiGroups: ["route.openshift.io"]
  resources:
    - routes
  verbs: ["get", "list", "watch"]

- apiGroups: ["image.openshift.io"]
  resources:
    - images
    - imagestreams
  verbs: ["get", "list", "watch"]

- apiGroups: ["build.openshift.io"]
  resources:
    - builds
    - buildconfigs
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps.openshift.io"]
  resources:
    - deploymentconfigs
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-mcp-server
  labels:
    app: openshift-mcp-server
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-mcp-server
subjects:
- kind: ServiceAccount
  name: openshift-mcp-server
  namespace: default

---
# Optional: Role for namespace-specific operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-mcp-server-namespace
  namespace: default
  labels:
    app: openshift-mcp-server
    component: monitoring
rules:
- apiGroups: [""]
  resources:
    - configmaps
    - secrets
    - events
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-mcp-server-namespace
  namespace: default
  labels:
    app: openshift-mcp-server
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-mcp-server-namespace
subjects:
- kind: ServiceAccount
  name: openshift-mcp-server
  namespace: default 