---
apiVersion: v1
kind: Service
metadata:
  name: openshift-mcp-server
  namespace: default
  labels:
    app: openshift-mcp-server
    component: monitoring
    version: v1.0.0
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: mcp
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: openshift-mcp-server
    component: monitoring
  sessionAffinity: None

---
# Optional: NodePort service for external access during development
apiVersion: v1
kind: Service
metadata:
  name: openshift-mcp-server-nodeport
  namespace: default
  labels:
    app: openshift-mcp-server
    component: monitoring
    version: v1.0.0
    service-type: nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: openshift-mcp-server
    component: monitoring
  sessionAffinity: None

---
# Optional: Headless service for StatefulSet or direct pod access
apiVersion: v1
kind: Service
metadata:
  name: openshift-mcp-server-headless
  namespace: default
  labels:
    app: openshift-mcp-server
    component: monitoring
    version: v1.0.0
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: openshift-mcp-server
    component: monitoring
  publishNotReadyAddresses: true 